# Generated by Django 5.2.3 on 2025-07-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
