# Generated by Django 5.2.3 on 2025-07-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_classroommember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'permissions': [('is_student', 'Is Student in this ckass'), ('is_teacher', 'Is Teacher in this class')]},
        ),
    ]
