# Generated by Django 5.2.3 on 2025-07-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_classroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'permissions': [('is_student', 'Is Student in this class'), ('is_teacher', 'Is Teacher in this class')]},
        ),
    ]
