# Generated by Django 5.2.3 on 2025-08-09 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_school_latitude_remove_school_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type_log', models.CharField(choices=[('info', 'Info'), ('debug', 'Debug'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=250)),
                ('desription', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
