# Generated by Django 5.2.3 on 2025-08-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='desription',
            new_name='description',
        ),
    ]
