# Generated by Django 5.2.3 on 2025-07-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_codemeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codemeli',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
