# Generated by Django 5.2.3 on 2025-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_codemeli_alter_user_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('modir', 'Modir'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10),
        ),
    ]
