# Generated by Django 5.2.3 on 2025-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codemeli',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
